# Generated by Django 3.0.5 on 2020-05-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200525_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='suncategory',
            new_name='subcategory',
        ),
    ]
